---
# docker compose up
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - "TRAEFIK_DASHBOARD_CREDENTIALS="admin:$$2y$$0aaaaaaaaaaaaa"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/traefik.yaml:ro"
      - "./dynamic.yaml:/dynamic.yaml:ro"
      - "./certs:/certs:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./traefik.yaml:/traefik.yaml:ro"
      - "./config.yaml:/config.yaml:ro"
      - "./logs:/var/log/traefik"

networks:
  proxy:
    external: true
